/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "landing-page": [],
    "login": [],
    "register": [],
    "home": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
